package scanner

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/sydlexius/mxlrcsvc-go/internal/app"
)

// minimalID3v2 is a minimal ID3v2.3 tag with TIT2 ("Test Title") and TPE1
// ("Test Artist") frames. dhowden/tag parses this without error.
// Generated by encoding TIT2 + TPE1 frames into a syncsafe-size ID3v2.3 header.
var minimalID3v2 = []byte{
	0x49, 0x44, 0x33, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2b, // ID3v2.3 header, syncsafe size=43
	0x54, 0x49, 0x54, 0x32, 0x00, 0x00, 0x00, 0x0b, 0x00, 0x00, // TIT2 frame header (size=11)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x54, 0x69, 0x74, 0x6c, 0x65, // encoding + "Test Title"
	0x54, 0x50, 0x45, 0x31, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, // TPE1 frame header (size=12)
	0x00, 0x54, 0x65, 0x73, 0x74, 0x20, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, // encoding + "Test Artist"
}

// writeAudioFile creates a minimal .mp3 in dir with a valid ID3v2 header.
func writeAudioFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, minimalID3v2, 0o644); err != nil {
		t.Fatalf("writeAudioFile %s: %v", path, err)
	}
}

// touchFile creates an empty file in dir.
func touchFile(t *testing.T, dir, name string) {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, nil, 0o644); err != nil {
		t.Fatalf("touchFile %s: %v", path, err)
	}
}

// TestGetSongDir_SkipLogic covers the 12-case skip-logic matrix:
// flags: (update, upgrade) × file states: (none, lrcOnly, txtOnly, both).
//
// Expected enqueue decisions (true = item added to queue):
//
//	update=false, upgrade=false:
//	  none      → true   (no existing lyrics, fetch fresh)
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → false  (txt present, not upgrading)
//	  both      → false  (lrc present, not updating)
//
//	update=false, upgrade=true:
//	  none      → true
//	  lrcOnly   → false  (lrc present, not updating)
//	  txtOnly   → true   (txt present, upgrade requested)
//	  both      → false  (lrc present, not updating)
//
//	update=true, upgrade=false (--update implies --upgrade):
//	  none      → true
//	  lrcOnly   → true   (update requested)
//	  txtOnly   → true   (update implies upgrade)
//	  both      → true
//
//	update=true, upgrade=true:
//	  (same as update=true, upgrade=false — all four cases enqueue)
func TestGetSongDir_SkipLogic(t *testing.T) {
	tests := []struct {
		name      string
		update    bool
		upgrade   bool
		lrcExists bool
		txtExists bool
		wantQueue bool
	}{
		// update=false, upgrade=false
		{name: "no_flags_no_files", update: false, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "no_flags_lrc_only", update: false, upgrade: false, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "no_flags_txt_only", update: false, upgrade: false, lrcExists: false, txtExists: true, wantQueue: false},
		{name: "no_flags_both", update: false, upgrade: false, lrcExists: true, txtExists: true, wantQueue: false},

		// update=false, upgrade=true
		{name: "upgrade_no_files", update: false, upgrade: true, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "upgrade_lrc_only", update: false, upgrade: true, lrcExists: true, txtExists: false, wantQueue: false},
		{name: "upgrade_txt_only", update: false, upgrade: true, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "upgrade_both", update: false, upgrade: true, lrcExists: true, txtExists: true, wantQueue: false},

		// update=true, upgrade=false
		{name: "update_no_files", update: true, upgrade: false, lrcExists: false, txtExists: false, wantQueue: true},
		{name: "update_lrc_only", update: true, upgrade: false, lrcExists: true, txtExists: false, wantQueue: true},
		{name: "update_txt_only", update: true, upgrade: false, lrcExists: false, txtExists: true, wantQueue: true},
		{name: "update_both", update: true, upgrade: false, lrcExists: true, txtExists: true, wantQueue: true},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			writeAudioFile(t, dir, "track.mp3")
			if tc.lrcExists {
				touchFile(t, dir, "track.lrc")
			}
			if tc.txtExists {
				touchFile(t, dir, "track.txt")
			}

			queue := app.NewInputsQueue()
			sc := NewScanner()
			// depth=0, limit=100, bfs=false
			if err := sc.GetSongDir(dir, queue, tc.update, tc.upgrade, 100, 0, false); err != nil {
				t.Fatalf("GetSongDir returned error: %v", err)
			}

			gotQueue := queue.Len() > 0
			if gotQueue != tc.wantQueue {
				t.Errorf("update=%v upgrade=%v lrc=%v txt=%v: got enqueued=%v, want enqueued=%v",
					tc.update, tc.upgrade, tc.lrcExists, tc.txtExists, gotQueue, tc.wantQueue)
			}
		})
	}
}
